apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  selector:
    app: javatemplate
  ports:
    - name: http
      port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
  type: ClusterIP